# Generated by Django 5.2.5 on 2025-09-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('google_book_id', models.CharField(max_length=22, unique=True, verbose_name='Google ID')),
                ('title', models.CharField(max_length=250, verbose_name='Titulo')),
                ('publisher', models.CharField(blank=True, max_length=100, null=True, verbose_name='Editora')),
                ('published_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data de Publicação')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('page_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='Numero de Paginas')),
                ('thumbnail_url', models.URLField(blank=True, null=True, verbose_name='URL da capa')),
                ('isbn_10', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='ISBN 10')),
                ('isbn_13', models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='ISBN 13')),
                ('authors', models.ManyToManyField(blank=True, related_name='books', to='google_books_app.authormodel', verbose_name='Autores')),
                ('categories', models.ManyToManyField(blank=True, related_name='books', to='google_books_app.categorymodel', verbose_name='Categorias')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'indexes': [models.Index(fields=['title'], name='google_book_title_2e2fec_idx'), models.Index(fields=['isbn_13'], name='google_book_isbn_13_5bfb42_idx'), models.Index(fields=['google_book_id'], name='google_book_google__e4ac4b_idx')],
            },
        ),
    ]
