# Generated by Django 5.2.5 on 2025-09-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='buy_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link de Compra'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Moeda'),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True),
        ),
    ]
