# Generated by Django 5.2.5 on 2025-09-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google_books_app', '0002_bookmodel_buy_link_bookmodel_currency_bookmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='URL da capa'),
        ),
    ]
