# Generated by Django 5.2.5 on 2025-09-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('known_for_department', models.CharField(max_length=100, verbose_name='Area de Atuação')),
                ('profile_path', models.CharField(max_length=250, verbose_name='Path foto de perfil')),
                ('tmdb_id', models.IntegerField(unique=True, verbose_name='Id author')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='DirectorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('profile_path', models.CharField(max_length=250, verbose_name='Path do Perfil')),
                ('tmdb_id', models.IntegerField(unique=True)),
            ],
            options={
                'verbose_name': 'Diretor',
                'verbose_name_plural': 'Diretores',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, verbose_name='Genero')),
                ('tmdb_id', models.CharField(max_length=50, verbose_name='TMDB Id')),
            ],
            options={
                'verbose_name': 'Genero',
                'verbose_name_plural': 'Generos',
            },
        ),
        migrations.CreateModel(
            name='LanguagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('language', models.CharField(max_length=100, unique=True, verbose_name='Linguagem')),
                ('iso_639_1', models.CharField(max_length=3, verbose_name='Abreviação')),
            ],
            options={
                'verbose_name': 'Linguagem',
                'verbose_name_plural': 'Linguagens',
            },
        ),
        migrations.CreateModel(
            name='ProductionCompaniesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nome Produtora')),
                ('origin_country', models.CharField(max_length=3, verbose_name='Origem')),
                ('logo_path', models.CharField(max_length=200, verbose_name='LogoTipo')),
                ('tmdb_id', models.IntegerField(verbose_name='ID pordutora')),
            ],
            options={
                'verbose_name': 'Produtora',
                'verbose_name_plural': 'Produtoras',
            },
        ),
        migrations.CreateModel(
            name='MoviesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=150, verbose_name='Titulo')),
                ('overview', models.TextField(verbose_name='Sinopse')),
                ('release_date', models.DateField(verbose_name='Data de Lançamento')),
                ('original_language', models.CharField(max_length=3, verbose_name='Idioma Original')),
                ('runtime', models.IntegerField(verbose_name='Duração em Minutos')),
                ('indicative_rating', models.CharField(max_length=100, verbose_name='Classificação Indicativa')),
                ('vote_average', models.FloatField(verbose_name='Média de Votos')),
                ('vote_count', models.IntegerField(verbose_name='Total de Votos')),
                ('poster_path', models.CharField(max_length=200, verbose_name='Path do Poster')),
                ('status', models.CharField(max_length=40, verbose_name='Status')),
                ('budget', models.IntegerField(verbose_name='Orçamento')),
                ('revenue', models.IntegerField(verbose_name='Receita')),
                ('popularity', models.FloatField(verbose_name='Popularidade')),
                ('tmdb_id', models.CharField(max_length=50, unique=True, verbose_name='Id tmdb')),
                ('cast', models.ManyToManyField(blank=True, related_name='filmes_atuados', to='movies_app.authormodel')),
                ('directors', models.ManyToManyField(blank=True, related_name='filmes_dirigidos', to='movies_app.directormodel')),
                ('genres', models.ManyToManyField(blank=True, related_name='filmes', to='movies_app.gender')),
                ('spoken_languages', models.ManyToManyField(blank=True, related_name='filmes', to='movies_app.languagesmodel')),
                ('production_companies', models.ManyToManyField(blank=True, related_name='filmes_produzidos', to='movies_app.productioncompaniesmodel')),
            ],
            options={
                'verbose_name': 'Filme',
                'verbose_name_plural': 'Filmes',
            },
        ),
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200, verbose_name='Titulo Filme')),
                ('key', models.CharField(max_length=200, verbose_name='Chave')),
                ('video_id', models.CharField(max_length=200, verbose_name='iD')),
                ('site', models.CharField(max_length=100, verbose_name='Site')),
                ('type', models.CharField(max_length=200)),
                ('filme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='movies_app.moviesmodels')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
            },
        ),
    ]
