# Generated by Django 5.2.5 on 2025-09-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moviesmodels',
            options={'verbose_name': 'Filme', 'verbose_name_plural': 'Filmes'},
        ),
    ]
