# Generated by Django 5.2.5 on 2025-09-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_app', '0002_alter_moviesmodels_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodels',
            name='cast',
            field=models.ManyToManyField(blank=True, null=True, related_name='filmes_atuados', to='movies_app.authormodel'),
        ),
        migrations.AlterField(
            model_name='moviesmodels',
            name='directors',
            field=models.ManyToManyField(blank=True, null=True, related_name='filmes_dirigidos', to='movies_app.directormodel'),
        ),
    ]
